#pragma once
#include <bpmn/bpmndi/bpmndiagram.h>
#include <bpmn/bpmndi/bpmnedge.h>
#include <bpmn/bpmndi/bpmnlabel.h>
#include <bpmn/bpmndi/bpmnplane.h>
#include <bpmn/bpmndi/bpmnshape.h>
#include <bpmn/dc/bounds.h>
#include <bpmn/dc/point.h>
#include <bpmn/di/diagram.h>
#include <bpmn/di/diagramelement.h>
#include <bpmn/di/edge.h>
#include <bpmn/di/label.h>
#include <bpmn/di/labelededge.h>
#include <bpmn/di/labeledshape.h>
#include <bpmn/di/node.h>
#include <bpmn/di/plane.h>
#include <bpmn/di/shape.h>
#include <bpmn/di/waypoint.h>
#include <bpmn/artifact.h>
#include <bpmn/association.h>
#include <bpmn/baseelement.h>
#include <bpmn/baseelement_p.h>
#include <bpmn/definitions.h>
#include <bpmn/documentation.h>
#include <bpmn/excusivegateway.h>
#include <bpmn/expression.h>
#include <bpmn/extension.h>
#include <bpmn/extensiondefinition.h>
#include <bpmn/flowelement.h>
#include <bpmn/flownode.h>
#include <bpmn/formalexpression.h>
#include <bpmn/gateway.h>
#include <bpmn/rootelement.h>
#include <bpmn/process.h>
#include <bpmn/sequenceflow.h>
#include <bpmn/outgoing.h>
#include <bpmn/incoming.h>
#include <bpmn/activity.h>
#include <bpmn/event.h>
#include <bpmn/startevent.h>
#include <bpmn/endevent.h>
#include <bpmn/extensionelements.h>
#include <bpmn/textannotation.h>
#include <bpmn/bpmnfactory.h>
